version: "2"
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    links:
      - app
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  app:    
    container_name: app
    image: keymetrics/pm2:latest-alpine
    volumes:
      - .:/var/www
    build: .
    ports:
      - "3000:3000"
    links:
      - elasticsearch
    networks:    
      - esnet    

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200    
    networks:
      - esnet        
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
